### ISSUE TITLE
[Enhancement] plugin:refresh command

### ISSUE THREAD

**Issue by FelixINX** [vojtasvoboda/oc-webartisan-plugin#2]
Hi,

First, you made a awesome plugin. Thank you!

The command `plugin:refresh` would be useful especially if you make a plugin on a shared host, without SSH, and without publishing on October marketplace.

URL could be :
`http://www.domain.com/artisan/v1/plugin/refresh/plugin_author/plugin_name/secret-hash`

So that would run `php artisan plugin:refresh plugin_author.plugin_name`.

Thanks!

**Comment by vojtasvoboda** [comment]
Hi,

I've just added required functionality and it is ready at market as update 1.0.2. Can you please test it?

http://octobercms.com/plugin/vojtasvoboda-webartisan

Thanks
Vojta

**Comment by FelixINX** [comment]
On my dev environment, it is working like a charm. Great work!

**Comment by vojtasvoboda** [comment]
Great! I will be more than happy for some plugin review :-) Thanks a lot
