### ISSUE TITLE
Exception after OctoberCMS update to version 428

### ISSUE THREAD

**Issue by Zelvar** [vojtasvoboda/oc-webartisan-plugin#3]
[CZ]

Po updatu Octoberu na verzi 428 jsem narazil na chybu uvedenou níže. 

Díky

---
[EN]
After update to latest version of October (428). I just wanted to refresh plugins plugins and I found this error.

Can you fix that or help me how can i fix it?

**`putenv() has been disabled for security reasons
.../vendor/symfony/console/Application.php line 103`**

![Screenshot](https://user-images.githubusercontent.com/2132876/33014450-a12a7016-cde7-11e7-887b-f496594f2ba2.png)

Thanks

**Comment by vojtasvoboda** [comment]
Díky za info, můžu poprosit o verzi PHP na jakém ti to běží? Koukám, že chyba padá přímo ze symfony/console.

**Comment by Zelvar** [comment]
Beží to na PHP 7.1

**Comment by vojtasvoboda** [comment]
Udělal jsem si nyní čistou instalaci OctoberCMS, na PHP:

```
λ php -v
PHP 7.1.11 (cli) (built: Nov  7 2017 18:18:38) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

OctoberCMS build 430. A vše funguje jak má.

Být tebou tak spíš zkusím vygooglit tu chybu `putenv() has been disabled for security reasons`, vypadá to, že na tvém hostingu, nebo lokálním serveru je toto zakázáno. Vím třeba, že na Wedosu to nefuguje, to mám odzkoušeno.

Řešení viz https://laravel.io/forum/04-16-2015-disabled-function-putenv
